# Generated by Django 2.2.5 on 2019-09-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=20)),
                ('Prezime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mjesec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oznaka', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=20)),
                ('Kod', models.CharField(max_length=20)),
                ('Cijena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Popis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrojRacuna', models.CharField(max_length=10)),
                ('Kupac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trgovinaweb.Kupac')),
                ('Mjesec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trgovinaweb.Mjesec')),
                ('Proizvod', models.ManyToManyField(to='trgovinaweb.Proizvod')),
            ],
        ),
    ]
